Examen/exam1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
]

Examen/home/urls.py
from django.urls import path
from home import views

app_name = 'home'

urlpatterns = [
    path('',views.index.as_view(), name = 'list_exam'),
    path('new/tarea/',views.NewTarea.as_view(), name = 'create_exam'),
    path('update/tarea/<int:pk>/',views.UpdateTarea.as_view(), name = 'update_exam'),
    path('delete/tarea/<int:pk>/',views.DeleteTarea.as_view(),name = 'delete_exam'),
    
    ###### Auditor URL
    path('list/auditor/',views.ListAuditor.as_view(), name = 'list_auditoria'),
    path('new/auditor/',views.NewAuditor.as_view(), name = 'create_auditoria'),
    path('update/auditor/<int:pk>/',views.UpdateAuditor.as_view(), name = 'update_auditoria'),
    path('delete/auditor/<int:pk>/',views.DeleteAuditor.as_view(),name = 'delete_auditoria'),
    
    
    ###### Aplicacion URL
    path('list/aplicacion',views.ListAplicacion.as_view(), name = 'list_aplication'),
    path('new/aplicacion/',views.NewAplicacion.as_view(), name = 'create_aplication'),
    path('update/aplicacion/<int:pk>/',views.UpdateAplicacion.as_view(), name = 'update_aplication'),
    path('delete/aplicacion/<int:pk>/',views.DeleteAplicacion.as_view(),name = 'delete_aplication'),
]

Examen/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}LISTA DE TAREA{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
        .bg-guinda { background-color: #800020; }
        .text-guinda { color: #800020; }
        .bg-gris { background-color: #f8f9fa; }
        .text-blanco { color: #ffffff; }
    </style>
</head>
<body class="bg-gris">
    <nav class="navbar navbar-expand-lg bg-guinda">
        <div class="container-fluid">
            <a class="navbar-brand text-blanco" href="#">Parras Dev</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active text-blanco" aria-current="page" href="{% url 'home:list_exam' %}">Lista Tarea</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-blanco" href="{% url 'home:list_auditoria' %}">Lista Auditores</a> 
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-blanco" href="{% url 'home:list_aplication' %}">Lista Aplicaciones</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- class body  -->
    <div class="container-xxl px-lg-5 pt-4 pb-5 pb-lg-0 mt-5 bg-white border border-secondary rounded">
        <div class="row">
            {% block content %}
            {% endblock content %}
        </div>  
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>  
</body>
</html>

Examen/templates/create_aplication.html
{% extends "base.html" %}

{% block title %}Nueva Task{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            {{ form }}
            <button type="submit" >New task</button>
            <a href="{% url 'home:list_exam' %}" >Cancel</a>
    </form>
{% endblock content %}

Examen/templates/create_auditar.html
{% extends "base.html" %}

{% block title %}Nueva  Auditoria{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            {{ form }}
            <button type="submit" >New task</button>
            <a href="{% url 'home:list_auditoria'%}" >Cancel</a>
    </form>
{% endblock content %}

Examen/templates/create_exam.html
{% extends "base.html" %}

{% block title %}Nueva Task{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            {{ form }}
            <button type="submit" >New task</button>
            <a href="{% url 'home:list_exam' %}" >Cancel</a>
    </form>
{% endblock content %}

Examen/templates/delete_aplication.html
{% extends "base.html" %}

{% block title %}Delete Task{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            {{ object }}
            <button type="submit">Delete task</button>
            <a href="{% url 'home:list_exam' %}" >Cancel</a>
    </form>
{% endblock content %}

Examen/templates/delete_auditar.html
{% extends "base.html" %}

{% block title %}Delete Task{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            {{ object }}
            <button type="submit">Delete task</button>
            <a href="{% url 'home:list_exam' %}" >Cancel</a>
    </form>
{% endblock content %}

Examen/templates/delete_exam.html
{% extends "base.html" %}

{% block title %}Delete Task{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            {{ object }}
            <button type="submit">Delete task</button>
            <a href="{% url 'home:list_exam' %}" >Cancel</a>
    </form>
{% endblock content %}

Examen/templates/list_aplication.html
{% extends "base.html" %}

{% block title %}To do{% endblock title %}

{% block content %}
  <h2>List</h2>
  <table class="table table-striped">
    <thead>
        <tr>
          <th scope="col">Nombre</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <a class="nav-link text-black" href="{% url 'home:create_aplication' %}">Create Aplication</a>
        {% for app in Aplicacion %}
        <tr>
            <td>{{ app.nombre}}</td>
            <td><a href="{% url 'home:update_aplication' app.pk %}"class="btn btn-outline-warning form-control">Update</td>
            <td><a href="{% url 'home:delete_aplication' app.pk %}"class="btn btn-outline-danger form-control">Delete</td>
        </tr>
        {%endfor%}
      </tbody>
  </table>
  
{% endblock content %}

Examen/templates/list_auditar.html
{% extends "base.html" %}

{% block title %}To do{% endblock title %}

{% block content %}
  <h2>list</h2>
  <table class="table table-striped">
    <thead>
        <tr>
          <th scope="col">Nombre</th>
          <th scope="col">Apellido</th>
          <th scope="col">Correo</th>
          <th scope="col">Telefono</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <a class="nav-link text-black" href="{% url 'home:create_auditoria' %}">Create auditar</a>
        {% for au in auditor %}
        <tr>
            <td>{{ au.nombre}}</td>
            <td>{{ au.apellido}}</td>
            <td>{{ au.correo}}</td>
            <td>{{ au.telefono}}</td>
            <td></td>
            <td><a href="{% url 'home:update_auditoria' au.pk %}"class="btn btn-outline-warning form-control">Update</td>
            <td><a href="{% url 'home:delete_auditoria' au.pk %}"class="btn btn-outline-danger form-control">Delete</td>
        </tr>
        {%endfor%}
      </tbody>
  </table>
  
{% endblock content %}

Examen/templates/list_exam.html
{% extends "base.html" %}

{% block title %}To do{% endblock title %}

{% block content %}
  <h2>Lista de Tareas </h2>
  <table class="table table-striped">
    <thead>
        <tr>
          <th scope="col">Descripcion</th>
          <th scope="col">Fecha de creacion</th>
          <th scope="col">Fecha Limite</th>
          <th scope="col">Estatus</th>
          <th scope="col">Responsable<th>
          <th scope="col">Acciones</th>
        </tr>
      </thead>
      <tbody>
        <a class="btn btn-outline-success" href="{% url 'home:create_exam' %}">Nueva Tarea</a>
        {% for task in tarea %}
        <tr>
            <td>{{ task.descripcion}}</td>
            <td>{{ task.fecha_creacion}}</td>
            <td>{{ task.fecha_limite}}</td>
            <td>{{ task.completada}}</td>
            <td>{{ task.auditor_asignado.apellido }}, {{ task.auditor_asignado.nombre }}</td>
            <td></td>
            <td><a href="{% url 'home:update_exam' task.pk %}"class="btn btn-outline-warning form-control">Actualizar</td>
            <td><a href="{% url 'home:delete_exam' task.pk %}"class="btn btn-outline-danger form-control">Borrar</td>
        </tr>
        {%endfor%}
      </tbody>
  </table>
  
{% endblock content %}

Examen/templates/update_aplication.html
{% extends "base.html" %}

{% block title %}Update Task{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            {{ form }}
            <button type="submit">Save</button>
            <a href="{% url 'home:list_exam' %}" >Cancel</a>
    </form>
{% endblock content %}

Examen/templates/update_auditar.html
{% extends "base.html" %}

{% block title %}Update Task{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            {{ form }}
            <button type="submit">Save</button>
            <a href="{% url 'home:list_exam' %}" >Cancel</a>
    </form>
{% endblock content %}

Examen/templates/update_exam.html
{% extends "base.html" %}

{% block title %}Update Task{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            {{ form }}
            <button type="submit">Save</button>
            <a href="{% url 'home:list_exam' %}" >Cancel</a>
    </form>
{% endblock content %}